# site name
prefixName: 
siteName: dummerfu
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/custom/avatar.jpg
url: https://dummerchen.github.io
description:  
cdn: #https://cdn.jsdelivr.net/gh/dummerchen/cdn@master
pjax: 1
# 1å¼€å¯
mathjax: 1

notice: false
lazyloadImg: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  é¦–é¡µ: { path: /, fa: fa-fort-awesome faa-shake }
  å½’æ¡£: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    æŠ€æœ¯: {path: /categories/æŠ€æœ¯/, fa: fa-code }, 
    éšç¬”: {path: /categories/éšç¬”/, fa: fa-file-text-o }, 
    # è½¬è½½: {path: /categories/è½¬è½½/, fa: fa-book },
    æ ‡ç­¾: {path: /tags, fa: fa-tags}
  } }
  # æ¸…å•: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
  #   å›¾é›†: {path: /tags/å›¾é›†/, fa: fa-photo }
  # } }
  # ç•™è¨€æ¿: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  å‹é“¾: { path: /links/, fa: fa-link faa-shake }
  contact: { path: /, fa: fa-heart faa-pulse ,submenus:{
    Gitee: { path: https://gitee.com/dummerchen, fa: iconfont icon-gitee2},
    Github: { path: http://github.com/dummerchen, fa: iconfont icon-github},
    cnblog: {path: https://www.cnblogs.com/cherrypill/,fa: iconfont icon-cnblogs},
  } }
  å…¶ä»–: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    å…³äºæˆ‘: {path: /about/, fa: fa-meetup}, 
    è¯´è¯´: {path: /shuoshuo/, fa: fa-commenting-o fa-commenting},
  } }


# Home page sort type: -1: newer firstï¼Œ1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# æ–‡ç« é¡µé¢æ˜¯å¦ä½¿ç”¨é¦–é¡µéšæœºå›¾
# å¦åˆ™ä½¿ç”¨æ–‡ç« çš„photos
is_use_random_post_bg: 0
# é¦–é¡µèƒŒæ™¯å›¾
bg:
  - https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/cover/1.png
  - https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/cover/2.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/cover/3.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/cover/4.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/cover/5.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/cover/6.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/cover/7.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/cover/8.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/cover/9.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/cover/10.jpg
  - 
# èƒŒæ™¯å›¾ç‰‡æ ·å¼ ç©º åŸå›¾æ•ˆæœ filter-dim é˜´å½± filter-grid æ¨ªæ¡ filter-dot ç‚¹ç‚¹
bgclass: 
post_article_bgclass: #"filter-dot"
# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: æœ¬ç«™ hexo ä¸»é¢˜, img: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: åšä¸»çš„bç«™è§†é¢‘, img: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/startdash/bilibili.jpg}
  - {url: /, title: dummerchençš„ä¸‡äº‹å±‹, desc: æŠ€æœ¯æœåŠ¡, img: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/startdash/wangshiwu.jpg}
# è‡ªå·±å¢åŠ çš„æ˜¯å¦ä½¿ç”¨startdash
usestartdash: 
  enable:false


# your site build time or founded date
siteBuildingTime: 11/22/2020

#social  url, img PCç«¯é…ç½®
social:
  github: {url: http://github.com/dummerchen, img: https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/social/github.png}
  zhihu: {url: https://www.zhihu.com/people/yi-cuo-zai-cuo-54, img: https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/social/zhihu.png}
  gitee: {url: https://gitee.com/dummerchen, img: https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/social/gitee.png}
  cnblog: {url: https://www.cnblogs.com/cherrypill/, img: https://cdn.jsdelivr.net/gh/dummerchen/cdn@2.0/img/social/cnblogs.png}

#social  url, img ç§»åŠ¨ç«¯é…ç½®
# ç›®å½•æ å¤´åƒä¸‹é¢çš„contact ä¸ªäººæ„Ÿè§‰å¤šæ­¤ä¸€ä¸¾
# msocial:
#   github: {url: http://github.com/dummerchen, fa: fa-github, color: 333}
  
donate:
  enable: false
  paypal: https://www.paypal.me/hojuncn
  alipay: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/custom/donate/AliPayQR.jpg
  wechat: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/custom/donate/WeChanQR.jpg
  wechatSQ: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/custom/donate/WeChanSQ.jpg

# è§†é¢‘åœ°å€ä¸ºhttps://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4ï¼Œé…ç½®å¦‚ä¸‹
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # å¤šä¸ªè§†é¢‘ç”¨é€—å·éš”å¼€ï¼Œéšæœºè·å–ã€‚æ”¯æŒçš„æ ¼å¼ç›®å‰å·²çŸ¥MP4,Flvã€‚å…¶ä»–çš„å¯ä»¥è¯•ä¸‹ï¼Œä¸ä¿è¯æœ‰ç”¨
  name: Unbroken.mp4

aplayer: 
  enable: false
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine:
  enable: false
  appId: Ipwy3hYofmpzH8YM1HdBoKnd-MdYXbMMI
  appKey: i7gXoRAlGyvp8NNEWntzV6KB
  enableQQ: true
  pageSize: 10
  placeholder: 'ğŸ“Œå¤´åƒå¯ä»¥å¡«å†™QQé‚®ç®±æ¥è‡ªåŠ¨è¡¥å…¨å•¦~\nğŸš€è¯„è®ºå’Œå›å¤æ”¯æŒMâ†“~'
# v_avatar: monsterid 

# Twikoo
twikoo:
  enable: true
  envId: twikoo-8g53l3ue41b208dc

widgetpack:
  enable: true
  id: 28857
  color: fc6423

# hexo-neat
# mdåšæ–‡å‹ç¼©
neat_enable: true
# å‹ç¼©htmlï¼ˆejsï¼Œswigç­‰ä¹Ÿå±äºhtmlæ ¼å¼ç‰‡æ®µï¼‰
neat_html:
  enable: true
  exclude:
# å‹ç¼©css  
neat_css:
  enable: true
  exclude:
    - '*.min.css'
    - '**/*.min.css'
    - 'jquery.fancybox.min.css'
# å‹ç¼©js
neat_js:
  enable: true
  mangle: true #æ‰“å°æ—¥å¿—
  output:
  compress:
  exclude: #æ’é™¤æ–‡ä»¶
    - '*.min.js'
    - '**/*.min.js'
    - 'jquery.fancybox.min.js'
