# site name
prefixName: 
siteName: dummerfu
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201018134428.jpg
url: https://dummerchen.github.io
description:  
cdn: #https://cdn.jsdelivr.net/gh/dummerchen/cdn@master
pjax: 1
# 1开启
mathjax: 1

notice: false
lazyloadImg: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    随笔: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友链: { path: /links/, fa: fa-link faa-shake }
  contact: { path: /, fa: fa-heart faa-pulse ,submenus:{
    Gitee: { path: https://gitee.com/dummerchen, fa: iconfont icon-gitee2},
    Github: { path: http://github.com/dummerchen, fa: iconfont icon-github},
    cnblog: {path: https://www.cnblogs.com/cherrypill/,fa: iconfont icon-cnblogs},
  } }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
  } }



# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/dummerchen/My_Image_Bed01@master/img/20201121172326.jpg
  - https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201102231714.jpg
  - https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201101194638.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/My_Image_Bed01@master/img/20201121172229.jpg
  - https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201115205545.jpg
  - https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201103125659.jpg
  - https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201103125638.jpg
  - https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201103130311.png
  - https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201107121121.jpg
  - https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201107121005.jpg
  - https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201107121655.jpg
  - https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201107121654.jpg
  - https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201115210146.jpg
  - https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201115210118.jpg
  - https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201115210440.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/My_Image_Bed01@master/img/20201121173038.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/My_Image_Bed01@master/img/20201119191328.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/My_Image_Bed01@master/img/20201119191259.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/My_Image_Bed01@master/img/20201119192651.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/My_Image_Bed01@master/img/20201119192521.png
  - https://cdn.jsdelivr.net/gh/dummerchen/My_Image_Bed01@master/img/20201119193802.png
  - https://cdn.jsdelivr.net/gh/dummerchen/My_Image_Bed01@master/img/20201119193902.jpg
  - https://cdn.jsdelivr.net/gh/dummerchen/My_Image_Bed01@master/img/20201119192304.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: 

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/startdash/bilibili.jpg}
  - {url: /, title: dummerchen的万事屋, desc: 技术服务, img: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/startdash/wangshiwu.jpg}
# 自己增加的是否使用startdash
usestartdash: enable:false


# your site build time or founded date
siteBuildingTime: 11/22/2020

#social  url, img PC端配置
social:
  github: {url: http://github.com/dummerchen, img: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/social/github.png}
  zhihu: {url: https://www.zhihu.com/people/yi-cuo-zai-cuo-54, img: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/social/zhihu.png}
  gitee: {url: https://gitee.com/dummerchen, img: https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201122224713.png}
  cnblog: {url: https://www.cnblogs.com/cherrypill/, img: https://gitee.com/dummerchen/MY_IMAGE_BED/raw/master/20201122224714.png}

#social  url, img 移动端配置
# 目录栏头像下面的contact 个人感觉多此一举
# msocial:
#   github: {url: http://github.com/dummerchen, fa: fa-github, color: 333}
  
donate:
  enable: false
  paypal: https://www.paypal.me/hojuncn
  alipay: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/custom/donate/AliPayQR.jpg
  wechat: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/custom/donate/WeChanQR.jpg
  wechatSQ: https://cdn.jsdelivr.net/gh/dummerchen/cdn@master/img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  enable: false
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ
